-- Unités : une seule écriture (« Kg », « kilo » → « kg » ; « cs » → « c. à soupe »…).
-- Même table que canonicalUnit (shared/units.ts).

UPDATE "Product" SET "unit" = NULL WHERE trim("unit") = '';
UPDATE "Product" SET "unit" = trim("unit") WHERE "unit" <> trim("unit");
UPDATE "Product" SET "unit" = CASE lower(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(trim("unit"), '.', ''), ' ', ''), '''', ''), '’', ''), 'à', 'a'), 'â', 'a'), 'À', 'a'), 'é', 'e'), 'è', 'e'), 'ê', 'e'), 'É', 'e'), 'È', 'e'), 'Ê', 'e'))
  WHEN 'kg' THEN 'kg'
  WHEN 'kgs' THEN 'kg'
  WHEN 'kilo' THEN 'kg'
  WHEN 'kilos' THEN 'kg'
  WHEN 'kilogramme' THEN 'kg'
  WHEN 'kilogrammes' THEN 'kg'
  WHEN 'kilogram' THEN 'kg'
  WHEN 'kilograms' THEN 'kg'
  WHEN 'g' THEN 'g'
  WHEN 'gr' THEN 'g'
  WHEN 'grs' THEN 'g'
  WHEN 'gramme' THEN 'g'
  WHEN 'grammes' THEN 'g'
  WHEN 'gram' THEN 'g'
  WHEN 'grams' THEN 'g'
  WHEN 'mg' THEN 'mg'
  WHEN 'milligramme' THEN 'mg'
  WHEN 'milligrammes' THEN 'mg'
  WHEN 'l' THEN 'L'
  WHEN 'lt' THEN 'L'
  WHEN 'ltr' THEN 'L'
  WHEN 'litre' THEN 'L'
  WHEN 'litres' THEN 'L'
  WHEN 'liter' THEN 'L'
  WHEN 'cl' THEN 'cl'
  WHEN 'centilitre' THEN 'cl'
  WHEN 'centilitres' THEN 'cl'
  WHEN 'ml' THEN 'ml'
  WHEN 'millilitre' THEN 'ml'
  WHEN 'millilitres' THEN 'ml'
  WHEN 'dl' THEN 'dl'
  WHEN 'decilitre' THEN 'dl'
  WHEN 'decilitres' THEN 'dl'
  WHEN 'piece' THEN 'pièce'
  WHEN 'pieces' THEN 'pièce'
  WHEN 'pc' THEN 'pièce'
  WHEN 'pcs' THEN 'pièce'
  WHEN 'unite' THEN 'pièce'
  WHEN 'unites' THEN 'pièce'
  WHEN 'cs' THEN 'c. à soupe'
  WHEN 'cas' THEN 'c. à soupe'
  WHEN 'casoupe' THEN 'c. à soupe'
  WHEN 'cuilasoupe' THEN 'c. à soupe'
  WHEN 'cuillereasoupe' THEN 'c. à soupe'
  WHEN 'cuilleresasoupe' THEN 'c. à soupe'
  WHEN 'cuillerasoupe' THEN 'c. à soupe'
  WHEN 'cuillersasoupe' THEN 'c. à soupe'
  WHEN 'cc' THEN 'c. à café'
  WHEN 'cac' THEN 'c. à café'
  WHEN 'cacafe' THEN 'c. à café'
  WHEN 'cuilacafe' THEN 'c. à café'
  WHEN 'cuillereacafe' THEN 'c. à café'
  WHEN 'cuilleresacafe' THEN 'c. à café'
  WHEN 'cuilleracafe' THEN 'c. à café'
  WHEN 'cuillersacafe' THEN 'c. à café'
  WHEN 'pincee' THEN 'pincée'
  WHEN 'pincees' THEN 'pincée'
END
WHERE lower(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(trim("unit"), '.', ''), ' ', ''), '''', ''), '’', ''), 'à', 'a'), 'â', 'a'), 'À', 'a'), 'é', 'e'), 'è', 'e'), 'ê', 'e'), 'É', 'e'), 'È', 'e'), 'Ê', 'e')) IN ('kg', 'kgs', 'kilo', 'kilos', 'kilogramme', 'kilogrammes', 'kilogram', 'kilograms', 'g', 'gr', 'grs', 'gramme', 'grammes', 'gram', 'grams', 'mg', 'milligramme', 'milligrammes', 'l', 'lt', 'ltr', 'litre', 'litres', 'liter', 'cl', 'centilitre', 'centilitres', 'ml', 'millilitre', 'millilitres', 'dl', 'decilitre', 'decilitres', 'piece', 'pieces', 'pc', 'pcs', 'unite', 'unites', 'cs', 'cas', 'casoupe', 'cuilasoupe', 'cuillereasoupe', 'cuilleresasoupe', 'cuillerasoupe', 'cuillersasoupe', 'cc', 'cac', 'cacafe', 'cuilacafe', 'cuillereacafe', 'cuilleresacafe', 'cuilleracafe', 'cuillersacafe', 'pincee', 'pincees');

UPDATE "RecipeIngredient" SET "unit" = NULL WHERE trim("unit") = '';
UPDATE "RecipeIngredient" SET "unit" = trim("unit") WHERE "unit" <> trim("unit");
UPDATE "RecipeIngredient" SET "unit" = CASE lower(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(trim("unit"), '.', ''), ' ', ''), '''', ''), '’', ''), 'à', 'a'), 'â', 'a'), 'À', 'a'), 'é', 'e'), 'è', 'e'), 'ê', 'e'), 'É', 'e'), 'È', 'e'), 'Ê', 'e'))
  WHEN 'kg' THEN 'kg'
  WHEN 'kgs' THEN 'kg'
  WHEN 'kilo' THEN 'kg'
  WHEN 'kilos' THEN 'kg'
  WHEN 'kilogramme' THEN 'kg'
  WHEN 'kilogrammes' THEN 'kg'
  WHEN 'kilogram' THEN 'kg'
  WHEN 'kilograms' THEN 'kg'
  WHEN 'g' THEN 'g'
  WHEN 'gr' THEN 'g'
  WHEN 'grs' THEN 'g'
  WHEN 'gramme' THEN 'g'
  WHEN 'grammes' THEN 'g'
  WHEN 'gram' THEN 'g'
  WHEN 'grams' THEN 'g'
  WHEN 'mg' THEN 'mg'
  WHEN 'milligramme' THEN 'mg'
  WHEN 'milligrammes' THEN 'mg'
  WHEN 'l' THEN 'L'
  WHEN 'lt' THEN 'L'
  WHEN 'ltr' THEN 'L'
  WHEN 'litre' THEN 'L'
  WHEN 'litres' THEN 'L'
  WHEN 'liter' THEN 'L'
  WHEN 'cl' THEN 'cl'
  WHEN 'centilitre' THEN 'cl'
  WHEN 'centilitres' THEN 'cl'
  WHEN 'ml' THEN 'ml'
  WHEN 'millilitre' THEN 'ml'
  WHEN 'millilitres' THEN 'ml'
  WHEN 'dl' THEN 'dl'
  WHEN 'decilitre' THEN 'dl'
  WHEN 'decilitres' THEN 'dl'
  WHEN 'piece' THEN 'pièce'
  WHEN 'pieces' THEN 'pièce'
  WHEN 'pc' THEN 'pièce'
  WHEN 'pcs' THEN 'pièce'
  WHEN 'unite' THEN 'pièce'
  WHEN 'unites' THEN 'pièce'
  WHEN 'cs' THEN 'c. à soupe'
  WHEN 'cas' THEN 'c. à soupe'
  WHEN 'casoupe' THEN 'c. à soupe'
  WHEN 'cuilasoupe' THEN 'c. à soupe'
  WHEN 'cuillereasoupe' THEN 'c. à soupe'
  WHEN 'cuilleresasoupe' THEN 'c. à soupe'
  WHEN 'cuillerasoupe' THEN 'c. à soupe'
  WHEN 'cuillersasoupe' THEN 'c. à soupe'
  WHEN 'cc' THEN 'c. à café'
  WHEN 'cac' THEN 'c. à café'
  WHEN 'cacafe' THEN 'c. à café'
  WHEN 'cuilacafe' THEN 'c. à café'
  WHEN 'cuillereacafe' THEN 'c. à café'
  WHEN 'cuilleresacafe' THEN 'c. à café'
  WHEN 'cuilleracafe' THEN 'c. à café'
  WHEN 'cuillersacafe' THEN 'c. à café'
  WHEN 'pincee' THEN 'pincée'
  WHEN 'pincees' THEN 'pincée'
END
WHERE lower(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(trim("unit"), '.', ''), ' ', ''), '''', ''), '’', ''), 'à', 'a'), 'â', 'a'), 'À', 'a'), 'é', 'e'), 'è', 'e'), 'ê', 'e'), 'É', 'e'), 'È', 'e'), 'Ê', 'e')) IN ('kg', 'kgs', 'kilo', 'kilos', 'kilogramme', 'kilogrammes', 'kilogram', 'kilograms', 'g', 'gr', 'grs', 'gramme', 'grammes', 'gram', 'grams', 'mg', 'milligramme', 'milligrammes', 'l', 'lt', 'ltr', 'litre', 'litres', 'liter', 'cl', 'centilitre', 'centilitres', 'ml', 'millilitre', 'millilitres', 'dl', 'decilitre', 'decilitres', 'piece', 'pieces', 'pc', 'pcs', 'unite', 'unites', 'cs', 'cas', 'casoupe', 'cuilasoupe', 'cuillereasoupe', 'cuilleresasoupe', 'cuillerasoupe', 'cuillersasoupe', 'cc', 'cac', 'cacafe', 'cuilacafe', 'cuillereacafe', 'cuilleresacafe', 'cuilleracafe', 'cuillersacafe', 'pincee', 'pincees');

UPDATE "ShoppingListItem" SET "unit" = NULL WHERE trim("unit") = '';
UPDATE "ShoppingListItem" SET "unit" = trim("unit") WHERE "unit" <> trim("unit");
UPDATE "ShoppingListItem" SET "unit" = CASE lower(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(trim("unit"), '.', ''), ' ', ''), '''', ''), '’', ''), 'à', 'a'), 'â', 'a'), 'À', 'a'), 'é', 'e'), 'è', 'e'), 'ê', 'e'), 'É', 'e'), 'È', 'e'), 'Ê', 'e'))
  WHEN 'kg' THEN 'kg'
  WHEN 'kgs' THEN 'kg'
  WHEN 'kilo' THEN 'kg'
  WHEN 'kilos' THEN 'kg'
  WHEN 'kilogramme' THEN 'kg'
  WHEN 'kilogrammes' THEN 'kg'
  WHEN 'kilogram' THEN 'kg'
  WHEN 'kilograms' THEN 'kg'
  WHEN 'g' THEN 'g'
  WHEN 'gr' THEN 'g'
  WHEN 'grs' THEN 'g'
  WHEN 'gramme' THEN 'g'
  WHEN 'grammes' THEN 'g'
  WHEN 'gram' THEN 'g'
  WHEN 'grams' THEN 'g'
  WHEN 'mg' THEN 'mg'
  WHEN 'milligramme' THEN 'mg'
  WHEN 'milligrammes' THEN 'mg'
  WHEN 'l' THEN 'L'
  WHEN 'lt' THEN 'L'
  WHEN 'ltr' THEN 'L'
  WHEN 'litre' THEN 'L'
  WHEN 'litres' THEN 'L'
  WHEN 'liter' THEN 'L'
  WHEN 'cl' THEN 'cl'
  WHEN 'centilitre' THEN 'cl'
  WHEN 'centilitres' THEN 'cl'
  WHEN 'ml' THEN 'ml'
  WHEN 'millilitre' THEN 'ml'
  WHEN 'millilitres' THEN 'ml'
  WHEN 'dl' THEN 'dl'
  WHEN 'decilitre' THEN 'dl'
  WHEN 'decilitres' THEN 'dl'
  WHEN 'piece' THEN 'pièce'
  WHEN 'pieces' THEN 'pièce'
  WHEN 'pc' THEN 'pièce'
  WHEN 'pcs' THEN 'pièce'
  WHEN 'unite' THEN 'pièce'
  WHEN 'unites' THEN 'pièce'
  WHEN 'cs' THEN 'c. à soupe'
  WHEN 'cas' THEN 'c. à soupe'
  WHEN 'casoupe' THEN 'c. à soupe'
  WHEN 'cuilasoupe' THEN 'c. à soupe'
  WHEN 'cuillereasoupe' THEN 'c. à soupe'
  WHEN 'cuilleresasoupe' THEN 'c. à soupe'
  WHEN 'cuillerasoupe' THEN 'c. à soupe'
  WHEN 'cuillersasoupe' THEN 'c. à soupe'
  WHEN 'cc' THEN 'c. à café'
  WHEN 'cac' THEN 'c. à café'
  WHEN 'cacafe' THEN 'c. à café'
  WHEN 'cuilacafe' THEN 'c. à café'
  WHEN 'cuillereacafe' THEN 'c. à café'
  WHEN 'cuilleresacafe' THEN 'c. à café'
  WHEN 'cuilleracafe' THEN 'c. à café'
  WHEN 'cuillersacafe' THEN 'c. à café'
  WHEN 'pincee' THEN 'pincée'
  WHEN 'pincees' THEN 'pincée'
END
WHERE lower(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(trim("unit"), '.', ''), ' ', ''), '''', ''), '’', ''), 'à', 'a'), 'â', 'a'), 'À', 'a'), 'é', 'e'), 'è', 'e'), 'ê', 'e'), 'É', 'e'), 'È', 'e'), 'Ê', 'e')) IN ('kg', 'kgs', 'kilo', 'kilos', 'kilogramme', 'kilogrammes', 'kilogram', 'kilograms', 'g', 'gr', 'grs', 'gramme', 'grammes', 'gram', 'grams', 'mg', 'milligramme', 'milligrammes', 'l', 'lt', 'ltr', 'litre', 'litres', 'liter', 'cl', 'centilitre', 'centilitres', 'ml', 'millilitre', 'millilitres', 'dl', 'decilitre', 'decilitres', 'piece', 'pieces', 'pc', 'pcs', 'unite', 'unites', 'cs', 'cas', 'casoupe', 'cuilasoupe', 'cuillereasoupe', 'cuilleresasoupe', 'cuillerasoupe', 'cuillersasoupe', 'cc', 'cac', 'cacafe', 'cuilacafe', 'cuillereacafe', 'cuilleresacafe', 'cuilleracafe', 'cuillersacafe', 'pincee', 'pincees');

UPDATE "Purchase" SET "unit" = NULL WHERE trim("unit") = '';
UPDATE "Purchase" SET "unit" = trim("unit") WHERE "unit" <> trim("unit");
UPDATE "Purchase" SET "unit" = CASE lower(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(trim("unit"), '.', ''), ' ', ''), '''', ''), '’', ''), 'à', 'a'), 'â', 'a'), 'À', 'a'), 'é', 'e'), 'è', 'e'), 'ê', 'e'), 'É', 'e'), 'È', 'e'), 'Ê', 'e'))
  WHEN 'kg' THEN 'kg'
  WHEN 'kgs' THEN 'kg'
  WHEN 'kilo' THEN 'kg'
  WHEN 'kilos' THEN 'kg'
  WHEN 'kilogramme' THEN 'kg'
  WHEN 'kilogrammes' THEN 'kg'
  WHEN 'kilogram' THEN 'kg'
  WHEN 'kilograms' THEN 'kg'
  WHEN 'g' THEN 'g'
  WHEN 'gr' THEN 'g'
  WHEN 'grs' THEN 'g'
  WHEN 'gramme' THEN 'g'
  WHEN 'grammes' THEN 'g'
  WHEN 'gram' THEN 'g'
  WHEN 'grams' THEN 'g'
  WHEN 'mg' THEN 'mg'
  WHEN 'milligramme' THEN 'mg'
  WHEN 'milligrammes' THEN 'mg'
  WHEN 'l' THEN 'L'
  WHEN 'lt' THEN 'L'
  WHEN 'ltr' THEN 'L'
  WHEN 'litre' THEN 'L'
  WHEN 'litres' THEN 'L'
  WHEN 'liter' THEN 'L'
  WHEN 'cl' THEN 'cl'
  WHEN 'centilitre' THEN 'cl'
  WHEN 'centilitres' THEN 'cl'
  WHEN 'ml' THEN 'ml'
  WHEN 'millilitre' THEN 'ml'
  WHEN 'millilitres' THEN 'ml'
  WHEN 'dl' THEN 'dl'
  WHEN 'decilitre' THEN 'dl'
  WHEN 'decilitres' THEN 'dl'
  WHEN 'piece' THEN 'pièce'
  WHEN 'pieces' THEN 'pièce'
  WHEN 'pc' THEN 'pièce'
  WHEN 'pcs' THEN 'pièce'
  WHEN 'unite' THEN 'pièce'
  WHEN 'unites' THEN 'pièce'
  WHEN 'cs' THEN 'c. à soupe'
  WHEN 'cas' THEN 'c. à soupe'
  WHEN 'casoupe' THEN 'c. à soupe'
  WHEN 'cuilasoupe' THEN 'c. à soupe'
  WHEN 'cuillereasoupe' THEN 'c. à soupe'
  WHEN 'cuilleresasoupe' THEN 'c. à soupe'
  WHEN 'cuillerasoupe' THEN 'c. à soupe'
  WHEN 'cuillersasoupe' THEN 'c. à soupe'
  WHEN 'cc' THEN 'c. à café'
  WHEN 'cac' THEN 'c. à café'
  WHEN 'cacafe' THEN 'c. à café'
  WHEN 'cuilacafe' THEN 'c. à café'
  WHEN 'cuillereacafe' THEN 'c. à café'
  WHEN 'cuilleresacafe' THEN 'c. à café'
  WHEN 'cuilleracafe' THEN 'c. à café'
  WHEN 'cuillersacafe' THEN 'c. à café'
  WHEN 'pincee' THEN 'pincée'
  WHEN 'pincees' THEN 'pincée'
END
WHERE lower(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(trim("unit"), '.', ''), ' ', ''), '''', ''), '’', ''), 'à', 'a'), 'â', 'a'), 'À', 'a'), 'é', 'e'), 'è', 'e'), 'ê', 'e'), 'É', 'e'), 'È', 'e'), 'Ê', 'e')) IN ('kg', 'kgs', 'kilo', 'kilos', 'kilogramme', 'kilogrammes', 'kilogram', 'kilograms', 'g', 'gr', 'grs', 'gramme', 'grammes', 'gram', 'grams', 'mg', 'milligramme', 'milligrammes', 'l', 'lt', 'ltr', 'litre', 'litres', 'liter', 'cl', 'centilitre', 'centilitres', 'ml', 'millilitre', 'millilitres', 'dl', 'decilitre', 'decilitres', 'piece', 'pieces', 'pc', 'pcs', 'unite', 'unites', 'cs', 'cas', 'casoupe', 'cuilasoupe', 'cuillereasoupe', 'cuilleresasoupe', 'cuillerasoupe', 'cuillersasoupe', 'cc', 'cac', 'cacafe', 'cuilacafe', 'cuillereacafe', 'cuilleresacafe', 'cuilleracafe', 'cuillersacafe', 'pincee', 'pincees');
